### PR TITLE
Voice recognition

### PR DESCRIPTION
**Pull request by ploiu**
This adds voice recognition capabilities to the main page. Until we can create our own grammar file, we are using Microsoft's grammar constraints which are downloaded and stored in memory through the speech recognizer's `compileConstraintsAsync` function

### CODE REVIEW

**Comment by ploiu** [comment]
All of those are good points. Microphone Permissions should not be requested when the app starts up, and it betrays user trust to get permission first and _then_ give them an option to disable it in the first time setup screen. It currently isn't clear to a user (who might not even know the assistant's name at first) how to activate him, and currently, bob isn't smart enough to listen again if the user just says "hey bob". 

For the issue of microphone permissions, I'm currently working on the settings and first time setup screens. I was thinking that after the first time setup screen is passed, if the user selected that they do want voice recognition, that we ask for voice recognition then. What's your thought on this?

For the issue of not knowing how to use bob, I can change it to display a welcome greeting on the main page for the first time the user hits the main page.

For the issue of bob not waiting enough, I can make a change to detect if the text is only "hey bob", and listen again if that's the case. Currently you can say it all in one shot, but yeah most people are so used to how Google and Alexa behave where they wait for a little bit that it would be a bad idea not to follow suit.

What are your opinions on those ideas? I think this pull request should wait until the settings changes get merged in, or if you want I can make the last 2 changes now and fix the microphone permission change in the settings branch I'm currently working on.

**Comment by strongr787** [comment]
I like waiting until sometime later in the process. Your idea sounds fine. 
I like something that gives a hint as to what to do. I had no clue until I read the code. Maybe something in the dynamic area that loads and has an example of commands available. maybe make the dynamic content only appear for say 30 seconds, then goes back to this screen that has commands on it
Having bob listen again if only hey bob is worth a shot. I didn't know if there was a timer or not. But if you can get that to work, then that sounds fine.

**Comment by ploiu** [comment]
I agree with most of that, except #2. I think reverting back the dynamic area will be annoying for users. What if the user is a bit slow at reading, and they ask for sometime (like a weather forecast) that takes them longer than the 30 seconds we give them? What if they want to come back to what's displayed on the screen later? I think a simple "what can you do?" Action would suffice for this, where Bob gives a couple of suggestions. Also after the user passes the first time setup screen, Bob can speak out loud to tell the user how to use him. That way we're giving instructions, but they don't happen all the time and therefore won't get in the way. What do you think?

**Comment by ploiu** [comment]
Well we will need a way to tell users how to use Bob, and I _think_ allowing for a pause after the "hey bob" is as simple as extending a timeout. I'll work on it either tonight or tomorrow. We have 3 weeks left before the capstone is due, and I think we're in a good place as long as we don't slow down.

**Comment by strongr787** [comment]
Alright sounds good. I almost forgot, are we still adding the button so the user can turn off continuous listening?

**Comment by ploiu** [comment]
Yes, I currently have that part working in the settings branch.

**Comment by ploiu** [comment]
@strongr787 I just allowed for a delay, how does it work out for you? I'll get the other parts done after the settings branch gets merged in to prevent merge conflicts since the changes I'd need to make affect the same files that the settings branch changes.

**Pull request merged**
